---
- name: Install prerequisites
  apt:
    name:
      - git
      - curl
    update_cache: yes

- name: Install Node.js (LTS)
  shell: |
      curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
      apt-get install -y nodejs
  args:
    creates: /usr/bin/node

- name: Clone app repo
  git:
    repo: https://github.com/SuchithraChandrasekaran/nodejs_service_deployment.git
    dest: /opt/nodejs-app
    version: main
    force: yes

- name: Install npm dependencies
  npm:
    path: /opt/nodejs-app
    production: yes

- name: Copy PM2 ecosystem file
  template:
    src: ecosystem.config.js.j2
    dest: /opt/nodejs-app/ecosystem.config.js

- name: Install pm2 globally
  npm:
    name: pm2
    global: yes

- name: Start or reload the service
  shell: |
    pm2 start /opt/nodejs-app/ecosystem.config.js || pm2 reload all
    pm2 save
