- hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install Node.js and npm
      apt:
        name:
          - nodejs
          - npm
        state: present
    - name: Create application file
      copy:
        dest: /home/ubuntu/app.js
        content: |
          const http = require('http');
          const server = http.createServer((req, res) => {
            res.end('Hello from Node.js on EC2!');
          });
          server.listen(3000);
    - name: Install pm2 globally
      npm:
        name: pm2
        global: yes
    - name: Start app with pm2
      shell: |
        pm2 start /home/ubuntu/app.js --name node-app
