name: Ansible Configure

on:
  workflow_run:
    workflows: ["Terraform Deploy"]
    types:
      - completed

jobs:
  configure:
    runs-on: self-hosted
    needs: terraform

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Ansible Playbook
        run: |
          PUBLIC_IP=$(terraform output -raw public_ip)
          ansible-playbook -i <<EOF inventory.ini
[ec2]
node ansible_host=$PUBLIC_IP ansible_user=ubuntu ansible_ssh_private_key_file=~/Downloads/democentralcanda.pem
EOF
          ansible-playbook playbook.yml
