name: Deploy Node.js App

on:
  push:
    branches:
      - main

jobs:
  terraform_apply:
    runs-on: [self-hosted, kinux]

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Init and Apply
        run: |
          terraform init
          terraform apply -auto-approve
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_public_key: ${{ secrets.TF_VAR_PUBLIC_KEY }}
          TF_VAR_key_name: "democentralcanada"


  ansible_deploy:
    needs: terraform_apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js (if needed)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Ansible and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo apt-add-repository --yes --update ppa:ansible/ansible
          sudo apt-get install -y ansible sshpass python3-pip

      - name: Create dynamic Ansible inventory with Terraform IP
        run: |
          echo "[nodejs-app]" > ansible/inventory.ini
          echo "${{ needs.terraform_apply.outputs.public_ip }} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/democentralcanada.pem" >> ansible/inventory.ini

      - name: Setup SSH Key and Known Hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/democentralcanada.pem
          chmod 600 ~/.ssh/democentralcanada.pem
          ssh-keyscan -H ${{ needs.terraform_apply.outputs.public_ip }} >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        run: |
          ansible-playbook ansible/node_service.yml \
            -i ansible/inventory.ini \
            --private-key ~/.ssh/democentralcanada.pem
